version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - project

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - project

    database:
        build: ./docker/mysql
        container_name: mysql
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/.dbdata:/var/lib/mysql
        networks:
            - project

    db_test:
        build: ./docker/mysql
        container_name: db_test
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'test'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3307:3307"
        networks:
            - project

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker/mysql/.redis:/data
        networks:
            - project

networks:
    project:
        driver: bridge




